version: "3.3"

services:
  apache:
    image: httpd:2.4
    ports:
      - ${PORT}:8075
    volumes:
      - ./www:/usr/local/apache2/htdocs
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/vhost.conf:/usr/local/apache2/conf/vhost.conf:ro
